FROM projeto/integrador

# Crie um diretório dentro da imagem
WORKDIR /app

# Copie a pasta do diretório local para dentro da imagem
COPY projetoIntegrador5 /app/projetoIntegrador5

# Execute comandos adicionais, se necessário
RUN comando1
RUN comando2

# Defina as configurações e variáveis do contêiner
ENV VARIAVEL=valor

# Especifique o comando de entrada padrão para o contêiner
CMD ["/bin/meu_comando"]
